version: '2'
services:
    elasticsearch:
        image: elasticsearch:2.3
        volumes:
        - ./data:/root/data
        ports:
        - "9200:9200"
        - "9300:9300"
    kibana:
        image: kibana:4.5
        ports:
        - "5601:5601"
        links:
        - elasticsearch
    jupyter:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
        - ./notebook:/home/jovyan/work
        ports:
        - "8888:8888"
        links:
        - elasticsearch
